[versions]

minecraft = "1.21.5"
parchment = "2025.06.15"

[libraries]

minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
parchment = { module = "org.parchmentmc.data:parchment-1.21.5", version.ref = "parchment" }