[versions]

minecraft = "1.21.11-pre1"
parchment = "2025.10.12"

[libraries]

minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
parchment = { module = "org.parchmentmc.data:parchment-1.21.10", version.ref = "parchment" } # TODO