[versions]

fabric-loader = "0.16.10"

kotlin = "2.2.0"

terrarium-cloche = "0.16.12"

[plugins]

kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

terrarium-cloche = { id = "earth.terrarium.cloche", version.ref = "terrarium-cloche" }