[versions]

kotlin = "2.2.0"
gson = "2.12.1"
ksp = "2.2.10-2.0.2"

stonecutter = "0.7.10"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
stonecutter = { id = "dev.kikugie.stonecutter", version.ref = "stonecutter" }